### ISSUE TITLE
Save ItemNTB from Head Database heads after placting and breaking

### ISSUE THREAD

**Issue by CloudeLecaw** [Arcaniax-Development/HeadDatabase-API#37]
When a head has some name and lore it got lost after placing.. sadly..

Well i saw plugins like EvenMoreFish that offer Heads that keep their Information
(They dont work with an extra database they get the info from the item itself. i aspect its saved in the ntb somewhere.)

HEre i made a video
https://streamable.com/24c74k

Would be nice to have this for Heads from Headdatabase too. because it often happens that someone placed a head somewhere. that was made as special item and not to be placed :3  

Before placing its namestring was:
![Snag_139c2d0](https://github.com/Zrips/CMI/assets/12080017/f4b4e8d8-588f-4526-b762-48e970eb6483)

Afer breaking it its namestring is:
![Snag_13a4176](https://github.com/Zrips/CMI/assets/12080017/de2effe7-9943-4ba5-8184-96c2b1934c57)

You see  currently after placing and breaking it aggain an HDB-Head losts moified name and lore and gets back his old Name that you can alsofind  in the HDB-database

**Comment by andrewkm** [comment]
This is the Github page for the API not the plugin.
Report your issues in the correct place: https://www.spigotmc.org/threads/head-database-paid.101767/

**Comment by CloudeLecaw** [comment]
closed because this is the api - the only seems to be exsting github for it...sadly
